# Intrductin to Numpy

In [73]:
import numpy as np
import pandas as pd

# Reading the example code

In [74]:
# one dimension numpy array
oneD = np.array([1,2,3,4,5,6,7,8])
print("Original Array " , oneD)
print("Data type of Array ", oneD.dtype)
print("shape of Array ", oneD.shape)

Original Array  [1 2 3 4 5 6 7 8]
Data type of Array  int32
shape of Array  (8,)


In [75]:
# Two dimension numpy array
twoD = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array ", twoD)
print("Data type of Array ", twoD.dtype)
print("shape of Array ", twoD.shape)

Original Array  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type of Array  int32
shape of Array  (3, 3)


# How to create a basic array

This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [76]:
# To create a NumPy array, you can use the function np.array().
simpleArr = np.array([1, 2, 3])
print("Simple Array : ", simpleArr)

# Array of zeros
zerosArr = np.zeros(5)
print("Zeros Array : ", zerosArr)

# Array of ones
onesArr = np.ones(5)
print("Ones Array : ", onesArr)

# empty Array
emptyArr = np.empty(5)
print("Empty Array : ", emptyArr)

Simple Array :  [1 2 3]
Zeros Array :  [0. 0. 0. 0. 0.]
Ones Array :  [1. 1. 1. 1. 1.]
Empty Array :  [1. 1. 1. 1. 1.]


# Numpy Arange()

In [77]:
# arange(stop)
rangeArr = np.arange(10)
print("Range Array : ", rangeArr)

# arange(start, stop)
rangeArr = np.arange(5, 10)
print("Range Array : ", rangeArr)

''' And even an array that contains a range of evenly spaced intervals.
To do this, you will specify the first number, last number, and the step size.'''
# start stop and step
evenArr = np.arange(0, 10, 2)
print("Even Array : ", evenArr)

Range Array :  [0 1 2 3 4 5 6 7 8 9]
Range Array :  [5 6 7 8 9]
Even Array :  [0 2 4 6 8]


# Numpy linspace()

In [78]:
# Return evenly spaced numbers over a specified interval.

linearSpace1 = np.linspace(2, 8, num=5)
print("First Example : ", linearSpace1)

# you can optionally exclude the end point
linearSpace2 = np.linspace(2, 8, num=5, endpoint=False)
print("Second Example : ", linearSpace2)

# If you want to know the exact distance between the generated values
# than use retstep
linearSpace3 = np.linspace(2, 8, num=5, retstep=True)
print("Third Example : ", linearSpace3)

First Example :  [2.  3.5 5.  6.5 8. ]
Second Example :  [2.  3.2 4.4 5.6 6.8]
Third Example :  (array([2. , 3.5, 5. , 6.5, 8. ]), 1.5)


# Adding, removing, and sorting elements

In [79]:
# Sorting an element is simple with np.sort()
arr = np.array([11,17,5,14,8])
print('Before Sorting : ', arr)
print('After Sorting : ', np.sort(arr))

Before Sorting :  [11 17  5 14  8]
After Sorting :  [ 5  8 11 14 17]


In [80]:
# You can concatenate them with np.concatenate().
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6, 4, 6, 7, 8])
combinedArr = np.concatenate((arr1,arr2))
print("Combined Array : ", combinedArr)

Combined Array :  [1 2 3 4 5 6 4 6 7 8]


In [81]:
# For deletion the you can do indexing to select the values you want
combinedArr[3:7]

array([4, 5, 6, 4])

# How do you know the shape and size of an array?

This section covers ndarray.ndim, ndarray.size, ndarray.shape

In [82]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [83]:
# To find the number of dimensions of the array, run:
print("Dimension of Array : ",array_example.ndim)

# To find the shape of the array, run:
print("Shape of the Array : ",array_example.shape)

# To find the size of the array, run:
print("Size of Array",array_example.size)

Dimension of Array :  3
Shape of the Array :  (3, 2, 4)
Size of Array 24


# Can you reshape an array?
# Yes!

In [84]:
a = np.arange(6)
print(a)
print(a.shape)
b = a.reshape(3, 2)
print(b)
print(b.shape)
c = b.reshape(1,6)
print(c)
print(c.shape)

[0 1 2 3 4 5]
(6,)
[[0 1]
 [2 3]
 [4 5]]
(3, 2)
[[0 1 2 3 4 5]]
(1, 6)


# How to convert a 1D array into a 2D array

In [85]:
originalArr = np.array([1, 2, 3, 4, 5, 6])
print(originalArr.shape)
row_vector = originalArr[np.newaxis, :]
print(row_vector.shape)
col_vector = originalArr[:, np.newaxis]
print(col_vector.shape)

(6,)
(1, 6)
(6, 1)


# Basic Array operations

In [86]:
# basic array operation
arr = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([2, 4, 6, 8, 10, 12])

# Accessing elements
print(arr[0])  # Output: 1
print(arr[2:5])  # Output: [3, 4, 5]
print(arr[1:]) 

# Updating elements
arr[1] = 7
print(arr)  # Output: [1, 7, 3, 4, 5, 6]

# Arithmetic operations
sum_arr = arr + arr2
print(sum_arr)  # Output: [3, 11, 9, 12, 15, 18]

diff_arr = arr - arr2
print(diff_arr)  # Output: [-1, 3, -3, -4, -5, -6]

prod_arr = arr * arr2
print(prod_arr)  # Output: [2, 28, 18, 32, 50, 72]

div_arr = arr / arr2
print(div_arr)  # Output: [0.5, 1.75, 0.5, 0.5, 0.5, 0.5]

# Aggregation functions
print(np.sum(arr))  # Output: 26
print(np.mean(arr)) # Output: 4.333333333333333
print(np.max(arr))  # Output: 7
print(np.min(arr))  # Output: 1

1
[3 4 5]
[2 3 4 5 6]
[1 7 3 4 5 6]
[ 3 11  9 12 15 18]
[-1  3 -3 -4 -5 -6]
[ 2 28 18 32 50 72]
[0.5  1.75 0.5  0.5  0.5  0.5 ]
26
4.333333333333333
7
1


In [87]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print("Minimum element in each Row", a.min(axis=0))  
print("Minimum element in each Column", a.min(axis=1)) 

Minimum element in each Row [0.12697628 0.05093587 0.26590556 0.5510652 ]
Minimum element in each Column [0.17296777 0.05093587 0.12697628]


In [134]:
# generating random number in numpy


(3, 4)
   0  1  2  3
0  7  8  4  4
1  1  7  6  9
2  4  1  5  9
